import Head from 'next/head';
import { Inter } from 'next/font/google';
import Header from '@/components/Header/Header';
import Sidebar from '@/components/Sidebar/Sidebar';
import Chat from '@/features/Chat/ChatPage';
import Input from '../../features/Chat/Input';
import { useCallback, useState } from 'react';
import { useAppDispatch, useAppSelector } from '@/store/hooks';
import { toggleSidebar, selectSidebar } from '../Sidebar/sidebarSlice';
type Props = { children: React.ReactNode };
export default function Layout({ children }: Props) {
    const [activeTab, setActiveTab] = useState('home');
    const handleTabChange = (tab: string) => {
        setActiveTab(tab);
    };
    // const [sidebarVisible, setSidebarVisible] = useState(false);
    // const toggleSidebar = () => {
    //     setSidebarVisible(!sidebarVisible);
    // };
    const isSidebarOpen = useAppSelector((state) => state.sidebar.open);
    const dispatch = useAppDispatch();
    const onClickSidebar = useCallback(() => dispatch(toggleSidebar()), [dispatch]);
    return (
        <div>
            <Head>
                <title>cb</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <div className='flex'>
                <Sidebar
                    activeTab={activeTab}
                    onTabChange={handleTabChange}
                    isSidebarOpen={isSidebarOpen}
                    toggleSidebar={onClickSidebar}
                />
                <main
                    className={`flex flex-col flex-grow h-screen transition-width duration-300 items-center justify-between
                    ${isSidebarOpen ? 'ml-64' : ''}`}
                >
                    <Header toggleSidebar={onClickSidebar} />
                    {/* <div className='debug-1'> */}
                    {children}

                    {/* </div> */}
                </main>
            </div>
        </div>
    );
}
