import Head from 'next/head';
import { Inter } from 'next/font/google';
import Header from '@/components/Header/Header';
import Sidebar from '@/components/Sidebar/Sidebar';
import Chat from '@/components/Chat/Chat';
import Input from '../Input';
import { useState } from 'react';
type Props = { children: React.ReactNode };
export default function Layout({ children }: Props) {
    const [activeTab, setActiveTab] = useState('home');
    const [sidebarVisible, setSidebarVisible] = useState(false);
    const toggleSidebar = () => {
        setSidebarVisible(!sidebarVisible);
    };
    const handleTabChange = (tab: string) => {
        setActiveTab(tab);
    };
    return (
        <div>
            <Head>
                <title>cb</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <div className='flex'>
                <Sidebar
                    activeTab={activeTab}
                    onTabChange={handleTabChange}
                    visible={sidebarVisible}
                    toggleSidebar={toggleSidebar}
                />
                <main
                    className={`flex flex-col flex-grow h-screen transition-width duration-300 items-center justify-between
                    ${sidebarVisible ? 'ml-64' : ''}`}
                >
                    <Header toggleSidebar={toggleSidebar} />
                    {/* <div className='debug-1'> */}
                    {children}
                    <Input />
                    {/* </div> */}
                </main>
            </div>
        </div>
    );
}
