import { useCallback, useState, useEffect } from 'react';

import clsx from 'clsx';
import Head from 'next/head';
import { useRouter } from 'next/router';

import Navbar from '@/components/Navbar/Navbar';
import Sidebar from '@/components/Sidebar/Sidebar';
import useWindowDimensions from '@/hooks/useWindowDimension';
import { setAll,  } from '@/store/chatsSlice';
import { useAppDispatch,  } from '@/store/hooks';
import { setAllRoles } from '@/store/rolesSlice';
import { Chat, Role,  } from '@/types';
import * as idb from '@/utils/indexedDB';

import Alert from './Alert';

type Props = { children: React.ReactNode };

export default function Layout({ children }: Props) {
    const dispatch = useAppDispatch();
    const { query } = useRouter();
    const { width } = useWindowDimensions();
    const [sidebarOpen, setSidebarOpen] = useState(true);
    const toggleSidebar = () => {
        setSidebarOpen(!sidebarOpen);
    };

    const [isLoading, setIsLoading] = useState(true);
    useEffect(() => {
        if (width && width <= 640 && sidebarOpen) {
            toggleSidebar();
        }
    }, [query.id]);

    useEffect(() => {
        const loadRecords = async () => {
            const roles: Role[] = await idb.get('roles');
            if (roles) {
                dispatch(setAllRoles(roles));
            }
            const chats: Chat[] = await idb.get('chats');
            if (chats) {
                dispatch(setAll(chats));
            }
            setIsLoading(false);
        };
        loadRecords();
    }, []);

    return isLoading ? (
        <div className="">loading...</div>
    ) : (
        <>
            <Head>
                <title>cb</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="fixed inset-0 flex h-screen">
                <Sidebar sidebarOpen={sidebarOpen} toggleSidebar={toggleSidebar} />
                <div className={clsx('relative flex w-full basis-full flex-col overflow-hidden')}>
                    <Navbar toggleSidebar={toggleSidebar} isSidebarOpen={sidebarOpen} />
                    {children}
                </div>
            </div>
            <Alert />
        </>
    );
}
